function stats = log_iterates(problem, x, stats)
% function stats = log_iterates(problem, x, stats)
%
% This small helper function is used to log the sequence of iterates 
% generated by the Riemannian Staircase

stats.Yvals = x';

end

